### ISSUE TITLE
Content check

### ISSUE THREAD

**Issue by janva** [janva/TDTS04#5]
Now check word for word, can't check combinations. ie britney spears now check britney and spears as separate words. Shall check "Britney Spears"  as one word.

**Comment by Carl-Martin** [comment]
Now checks line for line in forbidden.txt.
forbidden.txt can not contain empty lines (unless user wants to block all sites).

During url check the entire request line is parsed, meaning that if GET or something like 1.1 is included as a seperate entry in forbidden.txt, all sites will be blocked.
